/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppReportRouteImport } from './routes/_app.report'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppNavigateRouteImport } from './routes/_app.navigate'
import { Route as AppBuddiesRouteImport } from './routes/_app.buddies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppReportRoute = AppReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppNavigateRoute = AppNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => AppRoute,
} as any)
const AppBuddiesRoute = AppBuddiesRouteImport.update({
  id: '/buddies',
  path: '/buddies',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buddies': typeof AppBuddiesRoute
  '/navigate': typeof AppNavigateRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/buddies': typeof AppBuddiesRoute
  '/navigate': typeof AppNavigateRoute
  '/profile': typeof AppProfileRoute
  '/report': typeof AppReportRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/buddies': typeof AppBuddiesRoute
  '/_app/navigate': typeof AppNavigateRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/report': typeof AppReportRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/buddies' | '/navigate' | '/profile' | '/report'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/buddies' | '/navigate' | '/profile' | '/report'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/buddies'
    | '/_app/navigate'
    | '/_app/profile'
    | '/_app/report'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/report': {
      id: '/_app/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof AppReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/navigate': {
      id: '/_app/navigate'
      path: '/navigate'
      fullPath: '/navigate'
      preLoaderRoute: typeof AppNavigateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/buddies': {
      id: '/_app/buddies'
      path: '/buddies'
      fullPath: '/buddies'
      preLoaderRoute: typeof AppBuddiesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppBuddiesRoute: typeof AppBuddiesRoute
  AppNavigateRoute: typeof AppNavigateRoute
  AppProfileRoute: typeof AppProfileRoute
  AppReportRoute: typeof AppReportRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppBuddiesRoute: AppBuddiesRoute,
  AppNavigateRoute: AppNavigateRoute,
  AppProfileRoute: AppProfileRoute,
  AppReportRoute: AppReportRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
